apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: default
spec:
  serviceAccountName: prometheus
  # must match ServiceMonitor(s) label(s)
  serviceMonitorSelector:
    matchLabels:
      monitored: "true"
