apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-olm-metrics-monitor
  namespace: olmv1-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: olm-metrics-monitor
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: default
