apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-olm-metrics-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: olm-metrics-reader
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: default
